apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://mongo:27017/account
        - name: kafkabroker
          value: broker:29092
        image: us.icr.io/tfc-containers/tfc-app:latest
        name: app
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
