apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: transfer
  name: transfer
spec:
  ports:
  - name: "50052"
    port: 50052
    targetPort: 50052
  selector:
    io.kompose.service: transfer
status:
  loadBalancer: {}
