apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo

spec:
  replicas: 1
  selector:
    matchLabels:
      run: mongo
  template:
    metadata:
      labels:
        run: mongo
    spec:
      containers:
        - image: mongo:4.2.2-bionic
          name: mongo
          ports:
            - containerPort: 27017
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    run: mongo
  ports:
    - port: 27017