apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper

spec:
  selector:
    matchLabels:
      run: zookeeper
  template:
    metadata:
      labels:
        run: zookeeper
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: confluentinc/cp-zookeeper:5.3.1
          name: zookeeper
          ports:
            - containerPort: 2181
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    run: zookeeper
  ports:
    - port: 2181
